#include "p10f200.inc"
; CONFIG
    __CONFIG _WDT_OFF & _CP_OFF & _MCLRE_OFF
    ORG 0x0000
INIT
    MOVLW ~(1<<T0CS) ; ENABLE GPIO2
    OPTION; COPY CONTENT OF W REGISTER INTO OPTION REGISTER
    MOVLW B'11111001'; SET GP1 AND GP2 AS OUTPUTS
    TRIS GPIO; ; COPY CONTENTS OF W REGISTER INTO GPIO REGISTER
LOOP
    BSF GPIO, GP2; SET GP2 HIGH
    BCF GPIO, GP1; RESET GP1
    CALL DELAY ; CALL DELAY SUBROUTINE
    BCF GPIO, GP2; RESET GP2
    BSF GPIO, GP1; SET GP2 HIGH
    CALL DELAY; CALL DELAY SUBROUTINE
    GOTO LOOP; LOOP FOREVER
    
DELAY	; BEGINNING OF DELAY SUBROUTINE
    MOVLW D'5'; LOAD DELAY VALUE, THIS WILL RESULT IN DELAY OF APPROXIMATELY 1/8 OF A SECOND (162 LOOPS*255 LOOPS*3 CYCLES PER LOOP/1,000,000)= .12393 SECOND DELAY
    MOVWF 10; COPY F VALUE TO REGISTER 0X10
    MOVWF 11; COPY F VALUE TO REGISTER 0X11
    MOVWF 12; COPY F VALUE TO REGISTER 0X12
DELAY_LOOP
    DECFSZ 10, F ; DECREMENT REGISTER 0X10, AND CHECK IF NOT=0
    GOTO DELAY_LOOP; IF REG 0X10 NOT=0, GO BACK TO DELAY_LOOP (LINE 21)
    DECFSZ 11, F ; IF REG 0X10 =0, DECREMENT REGISTER 0X11, AND CHECK IF NOT=0
    GOTO DELAY_LOOP; IF REG 0X11 NOT=0, GO BACK TO DELAY_LOOP (LINE 21)
    DECFSZ 12, F ; DECREMENT REGISTER 0X12, AND CHECK IF NOT=0
    GOTO DELAY_LOOP; IF REG 0X12 NOT=0, GO BACK TO DELAY_LOOP (LINE 21)
    RETLW 0; IF REG 0X10 AND 0X11 ARE BOTH ZERO, RETURN FROM THE SUBROUTINE
    
    END


