#include "p10f200.inc" 
; CONFIG 
    __CONFIG _WDT_OFF & _CP_OFF & _MCLRE_OFF; TURN OFF WATCHDOG TIMER, CODE PROTECTION, AND RESET PIN (SO IT MAY BE USED AS GPIO)
    ORG 0x0000; ORIGIN, START OF PROGRAM
INIT; INITIALIZE MICROCONTROLLER ON NEXT THREE LINES
    MOVLW ~(1 << GP1); SET GP1 AS AN OUTPUT. MOVLW : MOVE LITERAL TO W; W: WORKING REGISTER; ~: NOT; (1 << GP1): INSERT 1 INTO REGISTER AT POSITION 0, SHIFT LEFT TO POSITION 1, SO TURN "00000001" INTO "00000010". ~ INVERTS "00000010" INTO "11111101".
    TRIS GPIO ; TRIS: TRI-STATE (LOW VOLT, HI VOLT, HIGH IMPEDANCE)
    BSF GPIO, GP1 ; SET GP1 OUTPUT HIGH TO LIGHT LED. BSF: BIT SET F. SET BITS MAKE PIN HIGH, CLR BIT MAKE BITS LOW
LOOP
    GOTO LOOP ; LOOP FOREVER
END ; END PROGRAM
    
    ;RECAP- INIT AND LOOP ARE LABELS
    ;MNEMONICS- MOVLW, TRIS, BSF - SEE ABOVE
    ;OPCODES AND OPERANDS: OPCODE- MOVLW, OPERAND- ~(1 << GP1)